//! Cross-wallet conformance: seed → public key → account address.
//!
//! Every crypto defect strkd has hit — the SNIP-12 digest (#7) and the declare
//! class hash (#9) — was drift found in production rather than by a test.
//! Converging with bramble on one account model (#16) is only worth anything if
//! something keeps the two converged, which is what this file is for (#17).
//!
//! ## What these vectors are, and what they are not
//!
//! `fixtures/conformance-vectors.json` was **generated by strkd and verified
//! against starknet.js** — specifically
//! `hash.calculateContractAddressFromHash(salt, class_hash, [public_key], 0)`,
//! which is exactly the call bramble makes. A vector that has only ever been
//! produced by strkd asserts nothing except that strkd is self-consistent, so
//! any change to the file must be re-checked against an independent
//! implementation before it lands.
//!
//! Bramble has no seed→address fixtures of its own to import: its krusty
//! adapter tests mock the WASM module, and real derivation is only exercised
//! end-to-end in Playwright. So this file is written to be adoptable *by*
//! bramble rather than copied *from* it. Until it runs on both sides, this
//! catches strkd drifting from the agreed model — not bramble drifting from
//! strkd.
//!
//! Public data only: paths, public keys, addresses. The mnemonic is the
//! published BIP-39 all-`abandon` test vector; never a real seed (spec §14).

use serde_json::Value;
use wallet_core::{
    account_address, address_hex, public_key, AccountContract, ChainId, Domain, Felt,
};

const VECTORS: &str = include_str!("fixtures/conformance-vectors.json");

fn doc() -> Value {
    serde_json::from_str(VECTORS).expect("conformance vectors must be valid JSON")
}

fn domain_of(name: &str) -> Domain {
    match name {
        "user" => Domain::User,
        "agent" => Domain::Agent,
        other => panic!("unknown domain in vectors: {other}"),
    }
}

#[test]
fn every_vector_reproduces() {
    let d = doc();
    let mnemonic = d["mnemonic"].as_str().unwrap();
    let vectors = d["vectors"].as_array().unwrap();
    assert!(!vectors.is_empty(), "the fixture must actually contain vectors");

    for v in vectors {
        let domain = domain_of(v["domain"].as_str().unwrap());
        let n = v["n"].as_u64().unwrap() as u32;
        let where_ = format!("{} account {n} ({})", v["domain"].as_str().unwrap(), v["path"]);

        assert_eq!(domain.path(n), v["path"].as_str().unwrap(), "path drifted for {where_}");

        let pk = public_key(mnemonic, domain, n, None).unwrap();
        assert_eq!(
            address_hex(&pk),
            v["public_key"].as_str().unwrap(),
            "public key drifted for {where_} — derivation itself changed",
        );

        let addr =
            account_address(mnemonic, domain, n, None, ChainId::Sepolia, AccountContract::OpenZeppelin)
                .unwrap();
        assert_eq!(
            address_hex(&addr),
            v["address"].as_str().unwrap(),
            "address drifted for {where_} — check the salt policy and class hash",
        );
    }
}

#[test]
fn the_fixture_pins_the_conventions_the_addresses_depend_on() {
    let d = doc();
    // If any of these move, every address moves with them — they are the
    // reason the vectors are what they are.
    assert_eq!(d["coin_type"].as_u64().unwrap() as u32, wallet_core::STARKNET_COIN_TYPE);
    assert_eq!(d["salt"].as_str().unwrap(), "0x0", "bramble salts OZ with zero");
    assert_eq!(d["account_contract"].as_str().unwrap(), "openzeppelin");
    assert_eq!(
        d["class_hash"].as_str().unwrap(),
        address_hex(&AccountContract::OpenZeppelin.class_hash(ChainId::Sepolia).unwrap()),
        "the OZ class hash moved — krusty's manifest changed under us",
    );
}

#[test]
fn the_vectors_cover_both_branches_and_more_than_the_first_account() {
    let d = doc();
    let vectors = d["vectors"].as_array().unwrap();
    let users = vectors.iter().filter(|v| v["domain"] == "user").count();
    let agents = vectors.iter().filter(|v| v["domain"] == "agent").count();
    // Account 0 was the one path both wallets agreed on even before #16, so a
    // suite covering only index 0 would have passed against the old, divergent
    // convention too.
    assert!(users > 1, "must cover more than user account 0");
    assert!(agents > 1, "must cover more than agent account 0");
}

#[test]
fn the_two_branches_never_produce_the_same_address() {
    let d = doc();
    let vectors = d["vectors"].as_array().unwrap();
    let mut seen = std::collections::HashSet::new();
    for v in vectors {
        let addr = v["address"].as_str().unwrap();
        assert!(seen.insert(addr), "duplicate address across vectors: {addr}");
        assert_ne!(Felt::from_hex(addr).unwrap(), Felt::ZERO);
    }
}

/// The agent branch must stay off the axis user accounts enumerate. A wallet
/// scanning account indices upward must never reach it.
#[test]
fn agent_vectors_sit_on_the_reserved_account_index() {
    let d = doc();
    for v in d["vectors"].as_array().unwrap() {
        if v["domain"] != "agent" {
            continue;
        }
        let path = v["path"].as_str().unwrap();
        assert!(
            path.contains(&format!("/{}'/", wallet_core::AGENT_ACCOUNT_INDEX)),
            "agent vector {path} is not on the reserved account index",
        );
    }
}
