//! STRK20 conformance vectors.
//!
//! `fixtures/strk20-vectors.json` is generated by this crate
//! (`STRK20_WRITE_VECTORS=1 cargo test -p strk20 --test vectors`) and checked
//! two ways: this test recomputes it with strkd, and `conformance/strk20.mjs`
//! recomputes every value independently with starknet.js. The SDK functions
//! these mirror are named next to each section.
//!
//! Keys come from the published BIP-39 all-`abandon` test vector; never a real
//! seed.

use krusty_kms_common::ChainId;
use serde_json::{json, Value};
use starknet_types_core::felt::Felt;
use strk20::actions::ClientAction;
use strk20::crypto::{self, EncChannelInfo, EncOutgoingChannelInfo, EncSubchannelInfo};
use strk20::hashes;
use strk20::invocation::ProofInvocation;
use wallet_core::{sign_hash, strk20_viewing_key, AccountContract, Domain};

const MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/strk20-vectors.json"
);

fn f(hex: &str) -> Felt {
    Felt::from_hex(hex).unwrap()
}
fn h(x: Felt) -> String {
    format!("{x:#x}")
}

/// Fixed inputs shared by the hash and encryption sections.
struct Inputs {
    a: Felt,
    b: Felt,
    c: Felt,
    d: Felt,
    index: u32,
    salt: Felt,
}

fn inputs() -> Inputs {
    Inputs {
        a: f("0x497e8446398aa1c30e6533382cedc0bca6df29f059fdbb227d9b727c04b7b4f"),
        b: f("0x2f6c0b3c1a9e5d4f8b7a6e5d4c3b2a19087f6e5d4c3b2a1908f7e6d5c4b3a29"),
        c: f("0x24680b5c991308b71103b02c2b17507e30ce70fc639fa9ef4de873c634f8270"),
        d: f("0x61e00fd6b5c92edccec6e9dce621f0ebb2d74795d148ed27bbf432507a20888"),
        index: 3,
        salt: f("0x1c0ffee5a17"),
    }
}

fn hash_vectors(i: &Inputs) -> Value {
    // SDK utils/hashes.ts
    json!({
        "identity_key": h(hashes::identity_key(i.a, i.b, i.c)),
        "enc_private_key_hash": h(hashes::enc_private_key_hash(i.a)),
        "enc_user_addr_hash": h(hashes::enc_user_addr_hash(i.a)),
        "enc_token_hash": h(hashes::enc_token_hash(i.a, i.index, i.salt)),
        "enc_channel_key_hash": h(hashes::enc_channel_key_hash(i.a)),
        "enc_sender_addr_hash": h(hashes::enc_sender_addr_hash(i.a)),
        "enc_recipient_addr_hash": h(hashes::enc_recipient_addr_hash(i.a, i.b, i.index, i.salt)),
        "channel_key": h(hashes::channel_key(i.a, i.b, i.c, i.d)),
        "outgoing_channel_id": h(hashes::outgoing_channel_id(i.a, i.b, i.index)),
        "channel_marker": h(hashes::channel_marker(i.a, i.b, i.c, i.d)),
        "subchannel_id": h(hashes::subchannel_id(i.a, i.index)),
        "subchannel_marker": h(hashes::subchannel_marker(i.a, i.b, i.c, i.d)),
        "note_id": h(hashes::note_id(i.a, i.c, i.index)),
        "enc_amount_hash": h(hashes::enc_amount_hash(i.a, i.c, i.index, i.salt)),
        "nullifier": h(hashes::nullifier(i.a, i.c, i.index, i.b)),
    })
}

fn encryption_vectors(i: &Inputs) -> Value {
    // SDK utils/encryptions.ts. The pool encrypts; strkd only decrypts, so the
    // ciphertexts are built from the primitives and the decryption checked.
    let (ephemeral_sk, recipient_sk) = (f("0x5eed1"), f("0x5eed2"));
    let (channel_key, sender) = (i.a, i.c);
    let shared = crypto::shared_x(ephemeral_sk, crypto::public_key(recipient_sk)).unwrap();
    let channel = EncChannelInfo {
        ephemeral_pubkey: crypto::public_key(ephemeral_sk),
        enc_channel_key: hashes::enc_channel_key_hash(shared) + channel_key,
        enc_sender_addr: hashes::enc_sender_addr_hash(shared) + sender,
    };
    let decrypted = crypto::decrypt_channel_info(&channel, recipient_sk).unwrap();
    assert_eq!((decrypted.key, decrypted.sender), (channel_key, sender));

    let token = i.d;
    let sub = EncSubchannelInfo {
        salt: i.salt,
        enc_token: hashes::enc_token_hash(channel_key, i.index, i.salt) + token,
    };
    assert_eq!(
        crypto::decrypt_subchannel_token(&sub, channel_key, i.index),
        token
    );

    let (amount, note_salt) = (
        1_000_000_000_000_000_000u128,
        0x0000_abcd_ef01_2345_6789_abcd_ef01_2345_u128,
    );
    let packed = crypto::encrypt_note_value(amount, note_salt, channel_key, token, i.index);
    assert_eq!(
        crypto::decrypt_note_value(packed, channel_key, token, i.index)
            .unwrap()
            .amount,
        amount
    );

    let recipient = i.d;
    let out = EncOutgoingChannelInfo {
        salt: i.salt,
        enc_recipient_addr: hashes::enc_recipient_addr_hash(sender, i.b, i.index, i.salt)
            + recipient,
    };
    assert_eq!(
        crypto::decrypt_outgoing_recipient(&out, sender, i.b, i.index),
        recipient
    );

    json!({
        "channel": {
            "ephemeral_sk": h(ephemeral_sk), "recipient_sk": h(recipient_sk),
            "channel_key": h(channel_key), "sender": h(sender),
            "ephemeral_pubkey": h(channel.ephemeral_pubkey),
            "enc_channel_key": h(channel.enc_channel_key), "enc_sender_addr": h(channel.enc_sender_addr),
        },
        "subchannel": { "channel_key": h(channel_key), "index": i.index, "salt": h(i.salt), "token": h(token), "enc_token": h(sub.enc_token) },
        "note": { "channel_key": h(channel_key), "token": h(token), "index": i.index, "amount": amount.to_string(), "salt": format!("{note_salt:#x}"), "packed_value": h(packed) },
        "outgoing": { "sender": h(sender), "sender_sk": h(i.b), "index": i.index, "salt": h(i.salt), "recipient": h(recipient), "enc_recipient_addr": h(out.enc_recipient_addr) },
    })
}

fn invocation_vector() -> Value {
    // SDK internal/proof-invocation-factory.ts: one action of every supported kind.
    let pool = f("0x3016a46eec8b164e8a89337c048b5cd1463ea4c4de120b9cb76b3df88646323");
    let user = wallet_core::account_address(
        MNEMONIC,
        Domain::User,
        0,
        None,
        ChainId::Sepolia,
        AccountContract::OpenZeppelin,
    )
    .unwrap();
    let user_sk = strk20_viewing_key(
        MNEMONIC,
        Domain::User,
        0,
        None,
        &ChainId::Sepolia.as_felt(),
        &pool,
    )
    .unwrap();
    let strk = f("0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d");
    let other = f("0x24680b5c991308b71103b02c2b17507e30ce70fc639fa9ef4de873c634f8270");
    let other_pk = f("0x61e00fd6b5c92edccec6e9dce621f0ebb2d74795d148ed27bbf432507a20888");
    let actions = vec![
        ClientAction::SetViewingKey { random: f("0x11") },
        ClientAction::OpenChannel {
            recipient_addr: other,
            index: 2,
            random: f("0x22"),
            salt: f("0x33"),
        },
        ClientAction::OpenSubchannel {
            recipient_addr: other,
            recipient_public_key: other_pk,
            channel_key: f("0xc4a2"),
            index: 0,
            token: strk,
            salt: f("0x44"),
        },
        ClientAction::Deposit {
            token: strk,
            amount: 10u128.pow(18),
        },
        ClientAction::UseNote {
            channel_key: f("0xc4a3"),
            token: strk,
            index: 5,
        },
        ClientAction::CreateEncNote {
            recipient_addr: other,
            recipient_public_key: other_pk,
            token: strk,
            amount: 2 * 10u128.pow(17),
            index: 0,
            salt: 0x55,
        },
        ClientAction::Withdraw {
            to_addr: user,
            token: strk,
            amount: 3 * 10u128.pow(17),
            random: f("0x66"),
        },
    ];
    let inv = ProofInvocation::new(pool, ChainId::Sepolia, Felt::ZERO, user, user_sk, &actions);
    let hash = inv.hash();
    let sig = sign_hash(MNEMONIC, Domain::User, 0, None, &hash).unwrap();
    let signature = AccountContract::OpenZeppelin.serialize_signature(&sig);
    json!({
        "chain_id": "SN_SEPOLIA",
        "pool": h(pool), "user": h(user), "user_sk": h(user_sk), "nonce": "0x0",
        "calldata": inv.calldata.iter().map(|x| h(*x)).collect::<Vec<_>>(),
        "transaction_hash": h(hash),
        "signature": signature.iter().map(|x| h(*x)).collect::<Vec<_>>(),
    })
}

fn generate() -> Value {
    let i = inputs();
    json!({
        "_provenance": "Generated by crates/strk20/tests/vectors.rs; re-derived independently by conformance/strk20.mjs (starknet.js). Test seed: the published BIP-39 all-abandon vector.",
        "inputs": { "a": h(i.a), "b": h(i.b), "c": h(i.c), "d": h(i.d), "index": i.index, "salt": h(i.salt) },
        "hashes": hash_vectors(&i),
        "encryption": encryption_vectors(&i),
        "invocation": invocation_vector(),
    })
}

#[test]
fn vectors_match_fixture() {
    let generated = generate();
    if std::env::var_os("STRK20_WRITE_VECTORS").is_some() {
        std::fs::write(
            FIXTURE,
            serde_json::to_string_pretty(&generated).unwrap() + "\n",
        )
        .unwrap();
    }
    let committed: Value =
        serde_json::from_str(&std::fs::read_to_string(FIXTURE).unwrap()).unwrap();
    assert_eq!(
        generated, committed,
        "strk20 vectors drifted from {FIXTURE}"
    );
}
